name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./CICD-Project.sln
      
    - name: Build
      run: dotnet build CICD-Project/CICD-Project.csproj --configuration Release --no-restore
      
    - name: Test
      run: dotnet test ./CICD-Project.sln --configuration Release --no-restore
       
    - name: Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: v0.7.0
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
#     - name: Docker build
#       run: |
#         docker build ./CICD-Project -t ${{ secrets.DOCKERHUB_USERNAME }}/cicd-project:dev
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        content: ./CICD-Project/
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/cicd-project:latest
